# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.2
language: objective-c
xcode_project: WBCategoryKit.xcworkspace
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

env:
- DESTINATION="OS=13.0,name=iPhone Xs" SCHEME="KeychainWrapper" SDK=iphonesimulator

notifications:
  email: true

pre:
  - xcrun instruments -w 'iPhone Xs (13.0)' || sleep 15

script:
- set -o pipefail
- xcodebuild -workspace 'Example/WBCategoryKit.xcworkspace' -scheme 'WBCategoryKit-Example' -configuration Debug -sdk iphonesimulator | xcpretty -c


#- pod lib lint
